name: Release

on:
  push:
    tags: [ v\d+.\d+.\d+ ]

jobs:
  create-release:
    permissions:
      contents: write
    runs-on: ubuntu-20.04
    outputs:
      release_id: ${{ steps.create-release.outputs.id }}
      release_upload_url: ${{ steps.create-release.outputs.upload_url }}
      release_body: "${{ steps.tag.outputs.message }}"

    steps:
      - uses: actions/checkout@v4

      - name: Get version
        id: get_version
        uses: battila7/actions-get-version@v2

      - name: Get tag message
        id: tag
        run: |
          git fetch --depth=1 origin +refs/tags/*:refs/tags/*
          echo "message<<EOF" >> $GITHUB_OUTPUT
          echo "$(git tag -l --format='%(contents)' ${{ steps.get_version.outputs.version }})" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create release
        id: create-release
        uses: ncipollo/release-action@v1
        with:
          draft: true
          name: ${{ steps.get_version.outputs.version }}
          tag: ${{ steps.get_version.outputs.version }}
          body: "${{ steps.tag.outputs.message }}"

  build-browser-extension:
    runs-on: ubuntu-20.04

    permissions:
      contents: write
      packages: write

    needs: create-release

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: latest
      
      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Get version
        id: get_version
        uses: battila7/actions-get-version@v2

      - name: Install dependencies
        run: pnpm install

      - name: Build browser extension
        run: pnpm run build

      - name: Package browser extension
        run: |
          mkdir release
          mv dist release/cooky-${{ steps.get_version.outputs.version-without-v }}
          cd release
          zip -r cooky-${{ steps.get_version.outputs.version-without-v }}.zip cooky-${{ steps.get_version.outputs.version-without-v }}/*

      - name: Upload browser extension to release
        id: update_release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.release_upload_url }}
          asset_path: ./release/cooky-${{ steps.get_version.outputs.version-without-v }}.zip
          asset_name: cooky-${{ steps.get_version.outputs.version-without-v }}.zip
          asset_content_type: application/zip
